config/routes.rb
Rails.application.routes.draw do
  resources :movies
  root :to => redirect('/movies')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/movie.rb
class Movie < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update destroy ]

  # GET /movies or /movies.json
  def index
    puts session[:sort]
    session[:sort] = session[:sort] || 'title'
    session[:direction] = session[:direction] || 'asc'
    puts session[:sort]
    if params[:sort]
      session[:sort] = params[:sort]
      session[:direction] = params[:direction]
    end
    puts session[:sort]
    sort_column = session[:sort]
    sort_direction = session[:direction]
    @movies = Movie.order("#{sort_column} #{sort_direction}")
  end

  # GET /movies/1 or /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy!

    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:title, :rating, :description, :release_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
    # def sortable(column, title = nil)
    #     title ||= column.titleize
    #     direction = (column == params[:sort] && params[:direction] == "asc") ? "desc" : "asc"
    #     link_to title, sort: column, direction: direction
    #   end
    def sort_indicator(column)
      if params[:sort] == column
        params[:direction] == "asc" ? "↑" : "↓"
      end
    end
    def sortable(column, title = nil)
      title ||= column.titleize
      direction = (column == params[:sort] && params[:direction] == "asc") ? "desc" : "asc"
      link_to title, { sort: column, direction: direction }, class: "sort-link"
    end
    def sort_class(column)
      params[:sort] == column ? params[:direction] : ""
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rottenpotatoes" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |form| %>
  <% if movie.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :rating, style: "display: block" %>
    <%= form.text_field :rating %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :release_date, style: "display: block" %>
    <%= form.text_field :release_date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/_movie.html.erb
<div id="<%= dom_id movie %>">
  <p>
    <strong>Title:</strong>
    <%= movie.title %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= movie.rating %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= movie.description %>
  </p>

  <p>
    <strong>Release date:</strong>
    <%= movie.release_date %>
  </p>

</div>

app/views/movies/edit.html.erb
<% content_for :title, "Editing movie" %>

<h1>Editing movie</h1>
<div class="form-container">
  <%= render "form", movie: @movie %>

  <br>

  <div>
    <%= link_to "Show this movie", @movie, class: 'button'  %> 
    <%= link_to "Back to movies", movies_path, class: 'button' %>
  </div>
</div>

app/views/movies/index.html.erb
<head>
  <%= stylesheet_link_tag 'movies', media: 'all' %>
</head>
<h1>MOVIES</h1>
<div class="page">
  <table class="movies">
    <thead>
      <tr>
        <% ['title', 'rating', 'release_date'].each do |col| %>
          <th class="<%= 'sorted-column ' + sort_class(col) if params[:sort] == col %>">
            <%= sortable(col, col.titleize) %> <%= sort_indicator(col) %>
          </th>
        <% end %>

        <th> </th>
      </tr>
    </thead>

    <tbody>
      <% @movies.each do |movie| %>
        <tr>
          <td class="<%= 'sorted-column ' + sort_class('title') if params[:sort] == 'title' %>"><%= movie.title %></td>
          <td class="<%= 'sorted-column ' + sort_class('rating') if params[:sort] == 'rating' %>"><%= movie.rating %></td>
          <td class="<%= 'sorted-column ' + sort_class('release_date') if params[:sort] == 'release_date' %>"><%= movie.release_date %></td>
          <td>
            <%= link_to "Show", movie %> |
            <%= link_to "Edit", edit_movie_path(movie) %> |
            <%= link_to "Delete", movie, method: :delete, data: { confirm: "Are you sure?" } %>
          </td>
        </tr>
      <% end %>
    </tbody>

    <tfoot>
      <tr>
        <td colspan="4">
          <%= link_to "+ New movie", new_movie_path %>
        </td>
      </tr>
    </tfoot>
  </table>
</div>

app/views/movies/new.html.erb
<% content_for :title, "New movie" %>

<h1>New movie</h1>

<div class="form-container">
  <%= render "form", movie: @movie %>
  
  <br>
  
  <div>
    <%= link_to "Back to movies", movies_path %>
  </div>
</div>

app/views/movies/show.html.erb
<p style="color: green"><%= notice %></p>

<h1>Movie Details</h1>

<div class="movie-details">
  <%= render @movie %>

  <div>
    <%= link_to "Edit this movie", edit_movie_path(@movie), class: 'button' %> 
    <%= link_to "Back to movies", movies_path , class: 'button' %>

    <%= button_to "Destroy this movie", @movie, method: :delete, class: 'button delete-button' %>
  </div>
</div>